apiVersion: v2
name: govital
description: A Go dependency maintenance scanner
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/steffakasid/govital
sources:
  - https://github.com/steffakasid/govital
maintainers:
  - name: Steffen Rumpf
    email: github@steffen-rumpf.de
    url: https://github.com/steffakasid
